alias av=aws-vault
alias ave="aws-vault exec"
alias avl="aws-vault login"
alias d=docker
alias dc=docker-compose
alias h=heroku
alias kc=kubectl
alias ls='ls -F'
alias tf=terraform
alias yt-dlmp3='yt-dlp -f ba -x --audio-format mp3'
