tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "coreutils"
brew "asdf"
brew "curl"
brew "gh"
brew "git"
brew "gitmoji"
brew "mackup"
brew "mas"
brew "pipx"
brew "starship"
brew "yadm"
cask "1password"
cask "font-sauce-code-pro-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "iterm2"
cask "visual-studio-code"
mas "Drafts", id: 1435957248
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
